repos:
  - repo: local
    hooks:
      - id: ruff
        name: Locked Ruff lint
        language: system
        entry: uv run --frozen --dev ruff check --fix
        types: [python]
      - id: ruff-format
        name: Locked Ruff format
        language: system
        entry: uv run --frozen --dev ruff format
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: djlint-reformat-jinja
        name: Locked Jinja format
        language: system
        entry: uv run --frozen --dev djlint --lint --reformat --profile=jinja
        files: ^app/templates/.*\.html$

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run --frozen --dev pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
      - id: ty
        name: ty
        entry: uv run --frozen --dev python scripts/check-types.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
