"""Add phase to wizard step

Revision ID: 20250913_add_phase_to_wizard_step
Revises: 39514b0aaad9
Create Date: 2025-09-13 21:25:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20250913_add_phase_to_wizard_step"
down_revision = "39514b0aaad9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wizard_step", schema=None) as batch_op:
        # Add the phase column with default value 'post' for backward compatibility
        batch_op.add_column(
            sa.Column("phase", sa.String(), nullable=False, server_default="post")
        )

        # Drop the old unique constraint
        batch_op.drop_constraint("uq_step_server_pos", type_="unique")

        # Create new unique constraint with phase included
        batch_op.create_unique_constraint(
            "uq_step_server_phase_pos", ["server_type", "phase", "position"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wizard_step", schema=None) as batch_op:
        # Drop the new unique constraint
        batch_op.drop_constraint("uq_step_server_phase_pos", type_="unique")

        # Recreate the old unique constraint
        batch_op.create_unique_constraint(
            "uq_step_server_pos", ["server_type", "position"]
        )

        # Drop the phase column
        batch_op.drop_column("phase")

    # ### end Alembic commands ###
